version: "3.8"

services:
  php:
    container_name: lib-php-health-check
    build:
      context: .
      dockerfile: ./docker/php8.1/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    user: $UID:$GID